businessCanvas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("canvas.urls")),
    path("", include("pwa.urls")),
    path("accounts/", include("django.contrib.auth.urls"))
]

canvas/urls.py
from django.urls import path
from . import views

app_name = "canvas"

urlpatterns = [
    path("", views.index, name="index"),
    path("add-partnership",
         views.addPartnership, name="add-partnership"),
    path("partnerships/<int:id>/delete",
         views.deletePartnership, name="delete-partnership"),
    path("add-activity",
         views.addActivity, name="add-activity"),
    path("activities/<int:id>/delete",
         views.deleteActivity, name="delete-activity"),
    path("add-resource",
         views.addResource, name="add-resource"),
    path("resources/<int:id>/delete",
         views.deleteResource, name="delete-resource"),
    path("add-proposition",
         views.addProposition, name="add-proposition"),
    path("propositions/<int:id>/delete",
         views.deleteProposition, name="delete-proposition"),
    path("add-customer-relationship",
         views.addCustomerRelationship, name="add-customer-relationship"),
    path("customer-relationships/<int:id>/delete",
         views.deleteCustomerRelationship, name="delete-customer-relationship"),
    path("add-channel",
         views.addChannel, name="add-channel"),
    path("channels/<int:id>/delete",
         views.deleteChannel, name="delete-channel"),
    path("add-customer-segment",
         views.addCustomerSegment, name="add-customer-segment"),
    path("customer-segments/<int:id>/delete",
         views.deleteCustomerSegment, name="delete-customer-segment"),
    path("add-cost-structure",
         views.addCostStructure, name="add-cost-structure"),
    path("cost-structures/<int:id>/delete",
         views.deleteCostStructure, name="delete-cost-structure"),
    path("add-revenue-stream",
         views.addRevenueStream, name="add-revenue-stream"),
    path("revenue-streams/<int:id>/delete",
         views.deleteRevenueStream, name="delete-revenue-stream"),
    path("about", views.about, name="about"),
    path("features", views.features, name="features"),
    path("contact", views.contact, name="contact"),
]

templates/components/navbar.html
<nav class="navbar navbar-expand-md navbar-light bg-light px-1 px-md-2">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'canvas:index' %}">
            BMC
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'canvas:about' %}">
                        About
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'canvas:features' %}">
                        Features
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'canvas:contact' %}">
                        Contact
                    </a>
                </li>
            </ul>
            {% if user %}
            <a href="{% url 'logout' %}" class="btn btn-outline-dark btn-sm">
                Logout
            </a>
            {% endif %}
        </div>
    </div>
</nav>