businessCanvas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("canvas.urls")),
    path("", include("pwa.urls")),
    path("accounts/", include("django.contrib.auth.urls"))
]

canvas/urls.py
from django.urls import path
from . import views

app_name = "canvas"

urlpatterns = [
    path("", views.index, name="index"),
    path("add-partnership",
         views.addPartnership, name="add-partnership"),
    path("partnerships/<int:id>/delete",
         views.deletePartnership, name="delete-partnership"),
    path("add-activity",
         views.addActivity, name="add-activity"),
    path("activities/<int:id>/delete",
         views.deleteActivity, name="delete-activity"),
    path("add-resource",
         views.addResource, name="add-resource"),
    path("resources/<int:id>/delete",
         views.deleteResource, name="delete-resource"),
    path("add-proposition",
         views.addProposition, name="add-proposition"),
    path("propositions/<int:id>/delete",
         views.deleteProposition, name="delete-proposition"),
    path("add-customer-relationship",
         views.addCustomerRelationship, name="add-customer-relationship"),
    path("customer-relationships/<int:id>/delete",
         views.deleteCustomerRelationship, name="delete-customer-relationship"),
    path("add-channel",
         views.addChannel, name="add-channel"),
    path("channels/<int:id>/delete",
         views.deleteChannel, name="delete-channel"),
    path("add-customer-segment",
         views.addCustomerSegment, name="add-customer-segment"),
    path("customer-segments/<int:id>/delete",
         views.deleteCustomerSegment, name="delete-customer-segment"),
    path("add-cost-structure",
         views.addCostStructure, name="add-cost-structure"),
    path("cost-structures/<int:id>/delete",
         views.deleteCostStructure, name="delete-cost-structure"),
    path("add-revenue-stream",
         views.addRevenueStream, name="add-revenue-stream"),
    path("revenue-streams/<int:id>/delete",
         views.deleteRevenueStream, name="delete-revenue-stream"),
    path("about", views.about, name="about"),
    path("features", views.features, name="features"),
    path("contact", views.contact, name="contact"),
]

canvas/models.py
from django.db import models


class KeyPartner(models.Model):
    class Meta:
        db_table = "KeyPartners"

    partner = models.CharField(max_length=50)


class KeyActivity(models.Model):
    class Meta:
        db_table = "KeyActivities"

    activity = models.CharField(max_length=100)


class KeyResource(models.Model):
    class Meta:
        db_table = "KeyResources"

    resource = models.CharField(max_length=200)


class ValueProposition(models.Model):
    class Meta:
        db_table = "ValuePropositions"

    proposition = models.CharField(max_length=100)


class CostStructure(models.Model):
    class Meta:
        db_table = "CostStructure"

    structure = models.CharField(max_length=100)


class CustomerRelationship(models.Model):
    class Meta:
        db_table = "CustomerRelationships"

    relationship = models.CharField(max_length=200)


class Channel(models.Model):
    class Meta:
        db_table = "Channels"

    channel = models.CharField(max_length=100)


class CustomerSegment(models.Model):
    class Meta:
        db_table = "CustomerSegments"

    segment = models.CharField(max_length=200)


class RevenueStream(models.Model):
    class Meta:
        db_table = "RevenueStreams"

    stream = models.CharField(max_length=100)

canvas/forms.py
from dataclasses import field
from django import forms
from .models import *


class AddPartnershipForm(forms.ModelForm):
    class Meta:
        model = KeyPartner
        fields = "__all__"


class AddActivityForm(forms.ModelForm):
    class Meta:
        model = KeyActivity
        fields = "__all__"


class AddResourceForm(forms.ModelForm):
    class Meta:
        model = KeyResource
        fields = "__all__"


class AddPropositionForm(forms.ModelForm):
    class Meta:
        model = ValueProposition
        fields = "__all__"


class AddCustomerRelationshipForm(forms.ModelForm):
    class Meta:
        model = CustomerRelationship
        fields = "__all__"


class AddChannelForm(forms.ModelForm):
    class Meta:
        model = Channel
        fields = "__all__"


class AddCustomerSegmentForm(forms.ModelForm):
    class Meta:
        model = CustomerSegment
        fields = "__all__"


class AddCostStructureForm(forms.ModelForm):
    class Meta:
        model = CostStructure
        fields = "__all__"


class AddRevenueStreamForm(forms.ModelForm):
    class Meta:
        model = RevenueStream
        fields = "__all__"

canvas/views.py
from importlib.resources import Resource
from pyexpat import model
from django.views.generic import DeleteView
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required

from .models import *
from .forms import *


@login_required
def index(request):
    partners = KeyPartner.objects.all()
    activities = KeyActivity.objects.all()
    resources = KeyResource.objects.all()
    propositions = ValueProposition.objects.all()
    cost_structures = CostStructure.objects.all()
    customer_relationships = CustomerRelationship.objects.all()
    customers = CustomerSegment.objects.all()
    channels = Channel.objects.all()
    revenues = RevenueStream.objects.all()

    return render(request, "canvas/index.html", {
        "partners": partners,
        "activities": activities,
        "resources": resources,
        "propositions": propositions,
        "cost_structures": cost_structures,
        "customer_relationships": customer_relationships,
        "customers": customers,
        "channels": channels,
        "revenues": revenues,
    })


# Partnership.
@login_required
def addPartnership(request):
    partner = request.POST["partner"]
    form = AddPartnershipForm({"partner": partner})
    if form.is_valid():
        form.save()
    return redirect('canvas:index')


@login_required
def deletePartnership(request, id=None):
    object = get_object_or_404(KeyPartner, id=id)
    object.delete()
    return redirect('canvas:index')


# Activities

@login_required
def addActivity(request):
    activity = request.POST["activity"]
    form = AddActivityForm({"activity": activity})
    if form.is_valid():
        form.save()
    return redirect('canvas:index')


@login_required
def deleteActivity(request, id=None):
    object = get_object_or_404(KeyActivity, id=id)
    object.delete()
    return redirect('canvas:index')


# Resources.

@login_required
def addResource(request):
    resource = request.POST["resource"]
    form = AddResourceForm({"resource": resource})
    if form.is_valid():
        form.save()
    return redirect('canvas:index')


@login_required
def deleteResource(request, id=None):
    object = get_object_or_404(KeyResource, id=id)
    object.delete()
    return redirect('canvas:index')

# Propositions


@login_required
def addProposition(request):
    proposition = request.POST["proposition"]
    form = AddPropositionForm({"proposition": proposition})
    if form.is_valid():
        form.save()
    return redirect('canvas:index')


@login_required
def deleteProposition(request, id=None):
    object = get_object_or_404(ValueProposition, id=id)
    object.delete()
    return redirect('canvas:index')

# Customer Relationship


@login_required
def addCustomerRelationship(request):
    relationship = request.POST["relationship"]
    form = AddCustomerRelationshipForm({"relationship": relationship})
    if form.is_valid():
        form.save()
    return redirect('canvas:index')


@login_required
def deleteCustomerRelationship(request, id=None):
    object = get_object_or_404(CustomerRelationship, id=id)
    object.delete()
    return redirect('canvas:index')

# Channels


@login_required
def addChannel(request):
    channel = request.POST["channel"]
    form = AddChannelForm({"channel": channel})
    if form.is_valid():
        form.save()
    return redirect('canvas:index')


@login_required
def deleteChannel(request, id=None):
    object = get_object_or_404(Channel, id=id)
    object.delete()
    return redirect('canvas:index')


# Customer Segments

@login_required
def addCustomerSegment(request):
    segment = request.POST["segment"]
    form = AddCustomerSegmentForm({"segment": segment})
    if form.is_valid():
        form.save()
    return redirect('canvas:index')


@login_required
def deleteCustomerSegment(request, id=None):
    object = get_object_or_404(CustomerSegment, id=id)
    object.delete()
    return redirect('canvas:index')


# Cost Structure

@login_required
def addCostStructure(request):
    structure = request.POST["structure"]
    form = AddCostStructureForm({"structure": structure})
    if form.is_valid():
        form.save()
    return redirect('canvas:index')


@login_required
def deleteCostStructure(request, id=None):
    object = get_object_or_404(CostStructure, id=id)
    object.delete()
    return redirect('canvas:index')


# Revenue Streams

@login_required
def addRevenueStream(request):
    stream = request.POST["stream"]
    form = AddRevenueStreamForm({"stream": stream})
    if form.is_valid():
        form.save()
    return redirect('canvas:index')


@login_required
def deleteRevenueStream(request, id=None):
    object = get_object_or_404(RevenueStream, id=id)
    object.delete()
    return redirect('canvas:index')


def about(request):
    return render(request, "canvas/about.html", {})


def features(request):
    return render(request, "canvas/features.html", {})


def contact(request):
    return render(request, "canvas/contact.html", {})

canvas/templates/canvas/components/activities.html
<div class="section">
    <h6>Key Activities</h6>
    <ul class="list-group">
        {% if activities %}
        {% for activity in activities %}
        <li>
            <div>
                <span class="counter green-counter"> {{ forloop.counter }}</span>
                {{ activity.activity }}
            </div>
            <a class="close-btn" href="{% url 'canvas:delete-activity' activity.id %}">
                x
            </a>
        </li>
        {% endfor %}
        {% else %}
        <p class="text-secondary">
            No key activities
        </p>
        {% endif %}
    </ul>
    <form class="form-inline mt-3" action="{% url 'canvas:add-activity' %}" method="post">
        {% csrf_token %}
        <input name="activity" type="text" placeholder="Add Activity" aria-label="Activity" />
        <button class="btn btn-outline-success my-2 my-sm-0 d-none" type="submit">
            Add
        </button>
    </form>
</div>

canvas/templates/canvas/components/channels.html
<div class="section">
    <h6>
        Channels
    </h6>
    <ul class="list-group">
        {% if channels %}
        {% for channel in channels %}
        <li>
            <div>
                <span class="counter green-counter"> {{ forloop.counter }}</span>
                {{ channel.channel }}
            </div>
            <a class="close-btn" href="{% url 'canvas:delete-channel' channel.id %}"> x </a>
        </li>
        {% endfor %}
        {% else %}
        <p class="text-secondary">
            No channels
        </p>
        {% endif %}
    </ul>
    <form class="form-inline mt-3" action="{% url 'canvas:add-channel' %}" method="post">
        {% csrf_token %}
        <input class="form-control mr-sm-2" name="channel" type="text" placeholder="Add Channel" aria-label="channel" />
        <button class="btn btn-outline-success my-2 my-sm-0 d-none" type="submit">
            Add
        </button>
    </form>
</div>

canvas/templates/canvas/components/cost-structure.html
<div class="section">
    <h6>
        Cost Structure
    </h6>
    <ul class="list-group">
        {% if cost_structures %}
        {% for cost_structure in cost_structures %}
        <li>
            <div>
                <span class="counter"> {{ forloop.counter }}</span>
                {{ cost_structure.structure }}
            </div>
            <a class="close-btn" href=" {% url 'canvas:delete-cost-structure' cost_structure.id %}">
                x
            </a>
        </li>
        {% endfor %}
        {% else %}
        <p class="text-secondary">
            No cost structures
        </p>
        {% endif %}
    </ul>
    <form class="form-inline mt-3" action="{% url 'canvas:add-cost-structure' %}" method="post">
        {% csrf_token %}
        <input name="structure" type="text" placeholder="Add Cost Structure" aria-label="Structure" />
        <button class="btn btn-outline-success my-2 my-sm-0 d-none" type="submit">
            Add
        </button>
    </form>
</div>

canvas/templates/canvas/components/customer-relationships.html
<div class="section">
    <h6>
        Customer Relationships
    </h6>
    <ul class="list-group">
        {% if customer_relationships %}
        {% for relationship in customer_relationships %}
        <li>
            <div>
                <span class="counter green-counter"> {{ forloop.counter }}</span>
                {{ relationship.relationship }}
            </div>
            <a class="close-btn" href="{% url 'canvas:delete-customer-relationship' relationship.id %}">
                x
            </a>
        </li>
        {% endfor %}
        {% else %}
        <p class="text-secondary">
            No customer relationships
        </p>
        {% endif %}
    </ul>
    <form class="form-inline mt-3" action="{% url 'canvas:add-customer-relationship' %}" method="post">
        {% csrf_token %}
        <input name="relationship" type="text" placeholder="Add Customer Relationship" aria-label="Relationship" />
        <button class="btn btn-outline-success my-2 my-sm-0 d-none" type="submit">
            Add
        </button>
    </form>
</div>

canvas/templates/canvas/components/customer-segments.html
<div class="section">
    <h6>
        Customer Segments
    </h6>
    <ul class="list-group">
        {% if customers %}
        {% for customer in customers %}
        <li>
            <div>
                <span class="counter"> {{ forloop.counter }}</span>
                {{ customer.segment }}
            </div>
            <a class="close-btn" href="{% url 'canvas:delete-customer-segment' customer.id %}"> x
            </a>
        </li>
        {% endfor %}
        {% else %}
        <p class="text-secondary">
            No Customer segments
        </p>
        {% endif %}
    </ul>
    <form class="form-inline mt-3" action="{% url 'canvas:add-customer-segment' %}" method="post">
        {% csrf_token %}
        <input name="segment" type="text" placeholder="Add Customer Segment" aria-label="Segment" />
        <button class="btn btn-outline-success my-2 my-sm-0 d-none" type="submit">
            Add
        </button>
    </form>
</div>

canvas/templates/canvas/components/partnership.html
<div class="section">
    <h6> Key Partnership </h6>
    <div class="list-container">
        <ul class="list-group">
            {% if partners %}
            {% for partner in partners%}
            <li class="show">
                <div>
                    <span class="counter"> {{ forloop.counter }}</span>
                    {{ partner.partner }}
                </div>
                <a class="close-btn" href="{% url 'canvas:delete-partnership' partner.id %}">
                    x
                </a>
            </li>
            {% endfor %}
            {% else %}
            <p class="text-secondary">
                No key partnerships
            </p>
            {% endif %}
        </ul>
    </div>
    <form class="form-inline mt-3" action="{% url 'canvas:add-partnership' %}" method="post">
        {% csrf_token %}
        <input name="partner" type="text" placeholder="Add Partnership" aria-label="Partner" />
        <button class="btn btn-outline-success my-2 my-sm-0 d-none" type="submit">
            Add
        </button>
    </form>
</div>

canvas/templates/canvas/components/propositions.html
<div class="section">
    <h6>Value Propositions</h6>
    <ul class="list-group">
        {%if propositions %}
        {% for proposition in propositions %}
        <li>
            <div>
                <span class="counter"> {{ forloop.counter }}</span>
                {{ proposition.proposition }}
            </div>
            <a class="close-btn" href="{% url 'canvas:delete-proposition' proposition.id %}">
                x
            </a>
        </li>
        {% endfor %}
        {% else %}
        <p class="text-secondary">
            No value propositions
        </p>
        {% endif %}
    </ul>
    <form class="form-inline mt-3" action="{% url 'canvas:add-proposition' %}" method="post">
        {% csrf_token %}
        <input name="proposition" type="text" placeholder="Add Proposition" aria-label="proposition" />
        <button class="btn btn-outline-success my-2 my-sm-0 d-none" type="submit">
            Add
        </button>
    </form>
</div>

canvas/templates/canvas/components/resources.html
<div class="section">
    <h6>
        Key Resources
    </h6>
    <ul class="list-group">
        {% if resources %}
        {% for resource in resources %}
        <li>
            <div>
                <span class="counter green-counter"> {{ forloop.counter }}</span>
                {{ resource.resource }}
            </div>
            <a class="close-btn" href="{% url 'canvas:delete-resource' resource.id %}">
                x
            </a>
        </li>
        {% endfor %}
        {% else %}
        <p class="text-secondary">
            No key resources
        </p>
        {% endif %}
    </ul>
    <form class="form-inline mt-3" action="{% url 'canvas:add-resource' %}" method="post">
        {% csrf_token %}
        <input name="resource" type="text" placeholder="Add Key Resource" aria-label="resource" />
        <button class="btn btn-outline-success my-2 my-sm-0 d-none" type="submit">
            Add
        </button>
    </form>
</div>

canvas/templates/canvas/components/revenue-streams.html
<div class="section">
    <h6>
        Revenue Streams
    </h6>
    <ul class="list-group">
        {% if revenues %}
        {% for revenue in revenues %}
        <li>
            <div>
                <span class="counter"> {{ forloop.counter }}</span>
                {{ revenue.stream }}
            </div>
            <a class="close-btn" href="{% url 'canvas:delete-revenue-stream' revenue.id %}">
                x
            </a>
        </li>
        {% endfor %}

        {% else %}
        <p class="text-secondary">
            No revenue streams
        </p>
        {% endif %}
    </ul>
    <form class="form-inline mt-3" action="{% url 'canvas:add-revenue-stream' %}" method="post">
        {% csrf_token %}
        <input name="stream" type="text" placeholder="Add Revenue Stream" aria-label="Stream" />
        <button class="btn btn-outline-success my-2 my-sm-0 d-none" type="submit">
            Add
        </button>
    </form>
</div>